### ISSUE TITLE
How best to manage the road map process

### ISSUE THREAD

**Issue by yanokwa** [getodk/roadmap#1]
We need to put together a community-driven road map. We've setup this repo and this issue tracker as a first step, but it's not clear it's the best way. If you have ideas about the best way to build a road map as a community, please add your feedback!

**Comment by yanokwa** [comment]
Fixed.

**Comment by jd-alexander** [comment]
Adding this comment here since it's associated with the roadmap. Should I create a seperate issue for the creation of a spec that would govern all the issues that are created for the roadmap?

**Comment by lognaturel** [comment]
Yes, a new issue would be great, @jd-alexander!
