### ISSUE TITLE
Briefcase & Aggregate: Add a GeoJSON export

### ISSUE THREAD

**Issue by ggalmazor** [getodk/roadmap#26]
### Background and strategic fit

ODK lets users define spatial fields (GEOPOINT, GEOTRACE, and GEOSHAPE) in their forms. Data in these fields is exported into CSV and JSON files in a way that commonly requires post-processing by users to make it compatible with downstream GIS software.

Typically, users want to use exported data directly in their third-party software apps.

[Forum discussion](https://forum.opendatakit.org/t/add-a-geojson-export-to-briefcase-and-aggregate/15184)

### Goals

Provide Aggregate and Briefcase with a new GeoJSON data export format

### Non-goals

- Provide complete submission representations
  - Only spatial data will be exported
  - Users will have to rely on other complete data exports to link spatial and non-spatial data.
- Produce files following the same structure than other existinging data exports
  - GeoJSON data will have a flat structure, including data from all repeat groups

### User stories

As a data manager, I would like to export data from Briefcase and Aggregate that I can more easily import into GIS or other downstream tools.

### Current functionality

- Aggregate can export submissions in CSV, and JSON format
- Briefcase can only export submissions in CSV format

### User interaction and design

**Exported GeoJSON data structure**

**Aggregate**

- We will provide a new option in the existing Export dialog:
  ![image](https://user-images.githubusercontent.com/205913/46027890-4dd01780-c0ef-11e8-9ed2-96d15d41b2cc.png)

**Briefcase**

- We will add a new select field to the default export configuration dialog to let the user choose which export format she wants:
  ![image](https://user-images.githubusercontent.com/205913/46028099-faaa9480-c0ef-11e8-9f26-87bc81357a44.png)

### Additional implementation details

- Jackson seems to be the way to go regarding serialization/deserialization of JSON objects. Aggregate already uses it, and there's already compatible library options to deal with GeoJSON objects on top of Jackson.
- The easier way to go about the implementation would be to start with Briefcase and produce something modular that could be copy&pasted to Aggregate

**GeoJSON output data structure**

We will export a root **FeatureCollection** that will include all spatial data from all submissions of a form.

Each GeoJSON object will have the following properties:
- `key`, containing the instance ID
  **Example**: `uuid:a8433b64-7b76-412f-b376-d48c6f0083a9`

  Locate the related submission by matching the `key` property on the GeoJSON object with the `KEY` column on the main output export file.

- `field`, containing the field name
  **Examples**: 
  - `some_field` (field at root level)
  - `uuid:a8433b64-7b76-412f-b376-d48c6f0083a9/some_group[42]/some_field`: 
`some_field` field in the 42th instance of the `some_group` repeat group from a particular instance

    Locate the related CSV row by matching the `field` property on the GeoJSON object with the `KEY` column on the corresponding repeat output export file.
<br/>

- `empty`, containing `yes` if the submission doesn't have an answer for that field, `no` otherwise
  This will let users filter GeoJSON data

- `valid` containing `yes` if the value was valid, `no` otherwise
  This will let users know which submissions and fields are experiencing problems

When a submission has no value for a spatial field, or the value is invalid, it will have the corresponding GeoJSON object type (Point, LineString, or Polygon) and will have a `null` `geometry` property

**GEOPOINT** fields will be encoded as Point GeoJSON objects:
- A GEOPOINT is a string containing space-separated, ordered, decimal-valued components:
  - The first value is the LATITUDE
  - The second value is the LONGITUDE
  - The third (optional) value is the ALTITUDE
  - The fourth (optional) value is the ACCURACY
- Invalid GEOPOINT representations include:
  - A latitude outside the range of -90.0 to 90.0
  - A longitude outside the range of -180.0 to 180.0
  - Less than 2 components
  - More than 4 components
  - Any non-decimal component

**GEOTRACE** fields will be encoded as LineString GeoJSON objects 
- A GEOTRACE is a string containing semicolon-separated GEOPOINT components
- Invalid GEOTRACE representations include:
  - Less than 2 components
  - Any no GEOPOINT component

**GEOSHAPE** fields will be encoded as Polygon objects
- A GEOSHAPE is a string containing semicolon-separated GEOPOINT components
- Invalid GEOSHAPE representations:
  - Less than 4 components
  - Different first and last components
  - Any no GEOPOINT component

### Alternatives considered

**Regarding exported GeoJSON data**

- We will start by including empty spatial fields but we could easily choose not to, or provide a toggle that would let users include them conditionally.

**Regarding the Briefcase UI**

- The GeoJSON output file could be provided as an extra output of the normal CSV export:
  ![image](https://user-images.githubusercontent.com/205913/46028411-cc798480-c0f0-11e8-981c-e55ce4c0ed61.png)

  _See the "Produce complementary GeoJSON file" checkbox_

**Comment by yanokwa** [comment]
Before this issue is closed, we should file an issue against Central to implement it.
