### ISSUE TITLE
Add an option to Briefcase export and Collect gdrive submission to remove group names in column headers.

### ISSUE THREAD

**Issue by aurdipas** [getodk/roadmap#27]
**Background**
When exporting a form from Aggregate or through Briefcase, variable names (column headers of the csv file) are not simply the one specified by the user on designing the form, but the eventual groups name the variable belong to, are automatically added before the actual name given to the variable.

In complex forms, with nested groups, this could lead in very long and complex names of column headers of the exported csv file.

These complex names bring complexity in the analysis and generate headache to data managers. 

The reason of generating these complex names when exporting data from Aggregate is due to the XForm specs that give the possibility to have variables with same name inside different groups.

Most ODK users use XLSForms or Build to create their forms that will not allow duplicated variable names but  data managers at the end need to manually (or with a specific manipulation post export) remove the group names for analysing the data. I

[Forum Post](https://forum.opendatakit.org/t/allow-more-control-over-variable-naming-syntax/15192/11)

**Goal** 

_a) Add an option to Briefcase to export without group names._
_b) Add and option to Aggregate to export to Google Sheets without group names._

These two options will work for forms that have been created with XLSForm and Build or with forms created manually (xml) without duplicated variable names.

In case of manually written xml files with duplicated variable names, a pop up could be shown to users after parsing the file, informing that due to duplicated variable names this kind of export can not be executed.

**Comment by lognaturel** [comment]
The conversation around Google Sheets was about the direct submission to sheets from Collect. The proposal was to add an option in Collect settings to not send the prefix.

It sounds like it would be helpful for Aggregate to also export without the prefixes. But this brings up a good question -- would providing that option for CSV export be sufficient or should it apply to all publishers including Google Sheets, etc?

**Comment by aurdipas** [comment]
@lognaturel I think it would be useful/helpful to to have also the option on Aggregate. Maybe as Briefcase/Collect/Aggregate are different projects, the feature should be tracked in 3 different issues? Work can start on one of the tools and then slowly into another. Maybe Briefcase is the easier to start with?

**Comment by yanokwa** [comment]
As discussed in our recent TSC call, we are closing this issue. It's been done in Briefcase and won't be done in Aggregate and we are only doing low risk, high value stuff there.
