### ISSUE TITLE
Change reasons

### ISSUE THREAD

**Issue by ggalmazor** [getodk/roadmap#32]
https://forum.opendatakit.org/t/approaches-for-linking-form-instance-changes-to-individuals/20189/8

**Comment by lognaturel** [comment]
Support starts in ODK Collect v1.25, pyxform 1.0.0, XLSForm Online v2.0.0. Documentation is at https://docs.opendatakit.org/form-audit-log/#tracking-reason-for-edit

Thanks for moving it to done, @ggalmazor. 🎉 I think it can also be closed!
