### ISSUE TITLE
Open selects

### ISSUE THREAD

**Issue by ggalmazor** [getodk/roadmap#33]
https://forum.opendatakit.org/t/allow-custom-choices-for-selects-that-get-saved-to-the-same-field-xforms-open-selects/22788

- [x] xfroms-specs issue: https://github.com/opendatakit/xforms-spec/issues/249
- [ ] javarosa issue
- [ ] collect issue

**Comment by tiritea** [comment]
FYI I implemented open selections for iXForms, so I have some ideas (eg how to display, etc) and insight that might be useful for a Collect implementation
