### ISSUE TITLE
Integration of OpenMapKit into Collect

### ISSUE THREAD

**Issue by ggalmazor** [getodk/roadmap#35]

**Comment by danbjoseph** [comment]
- there's a [Google Doc](https://docs.google.com/document/d/18ICz7gziV-8uiwy_lMDQ5PM_dD_fBmlcJKG_UJsMNUA/edit) discussing various spec considerations, user stories, etc
- deciding how to collect additional attributes on geographic features is tied to decisions made around longitudinal data collection in #23 
- [Selecting a map feature to collect data about](https://forum.getodk.org/t/selecting-a-map-feature-to-collect-data-about/28466) (forum thread)
- [Ability to load locations into the geowidget to guide data collection](https://forum.getodk.org/t/ability-to-load-locations-into-the-geowidget-to-guide-data-collection/27406) (forum thread)

**Comment by lognaturel** [comment]
Closing now that we have select one from map: https://docs.getodk.org/form-question-types/#select-one-from-map-widget

There's more we can do here of course and that's tracked in the forum features category and on the Collect repo.
