### ISSUE TITLE
Dependent value updates (lightweight timestamping, dynamic defaults)

### ISSUE THREAD

**Issue by yanokwa** [getodk/roadmap#4]
- [x] JavaRosa: https://github.com/opendatakit/javarosa/issues/227
- [x] XLSForm
- [x] pyxform

**Comment by lognaturel** [comment]
Part of this still needs a spec. We have support for dynamic defaults on form load but we don't have anything in XLSForm that lets us access the [`xforms-value-changed` event](https://opendatakit.github.io/xforms-spec/#event:xforms-value-changed).

**Comment by lognaturel** [comment]
Pending XLSForm Online release and docs merge.

**Comment by lognaturel** [comment]
http://xlsform.org/en/#trigger
http://xlsform.org/en/#default
