### ISSUE TITLE
ODK Aggregate to Central migration strategy

### ISSUE THREAD

**Issue by ggalmazor** [getodk/roadmap#43]
(needs governance doc?)

* https://forum.opendatakit.org/t/upcoming-changes-to-aggregate/17582
* https://forum.opendatakit.org/t/whats-coming-in-central-over-the-next-few-years/19677

Do we need more than the above?

**Comment by aurdipas** [comment]
this is marked done but still open. Is there anywhere a documentation to perform a migration from Aggregate to central?

**Comment by lognaturel** [comment]
As @aurdipas says, there's still some work to be done on Briefcase and documentation. This is captured by https://github.com/getodk/briefcase/pull/872.
