### ISSUE TITLE
External funding strategy (for code, docs, ...)

### ISSUE THREAD

**Issue by ggalmazor** [getodk/roadmap#46]
Try to get non-Nafundi people to contribute to core code.

Consortia for pursuing funding and how would something like that work? Letters of support or some such from end-users like Red Cross?

**Comment by lognaturel** [comment]
ODK's primary funding source is now [ODK Cloud](https://getodk.org/), the SaaS offering of Central. We consider implementation- and support-focused contracts on a case-by-case basis.
