### ISSUE TITLE
Create automatic background recording of interview

### ISSUE THREAD

**Issue by lognaturel** [getodk/roadmap#58]
High-level forum feature thread: https://forum.getodk.org/t/create-automatic-background-recording-of-interview-in-collect/18601

- [x] XLSForm spec
- [x] XForms spec
- [x] Collect user experience design

### Use cases

* As a user I'd like to be able to record audio and submit them as part of the form without leaving the form page
* As a survey administrator, I'd like to record entire surveys (or sections of a survey), not only single questions. The goal is to have a parallel audio file that would allow us to compare actual responses with how they were coded by the enumerator.

### Feature details

- The recording should be done in the background while the enumerator asks questions and receives responses
- The presence of a new metaquestion, similar to the existing audit metaquestion, in the XForm will indicate that background audio recording has been requested by the form author
- The presence of a corresponding setting in pyxform to control the XForm metaquestion in XLSForm
- There should be a configurable setting in the application on whether to allow background recordings. If a form requests it but the application settings have not allowed it then the user should see a notification asking them to enable it. However, not enabling the setting should not prevent someone to fill the form.
- Ideally, both the survey administrator and the application user should be able to set the recording quality and file type. If nothing is set, a default (low quality?) setting should be used. The application user's setting would override the survey designer's setting, if present. 
- File size is an issue when submitting in some environments, but for this feature we should assume that sufficient bandwidth is available. If time permits, this work could include a setting in Collect to send XML submissions without attachments, so that recordings can be copied offline without stopping regular submissions.

**Comment by tinok** [comment]
I added use cases and feature details to the issue description, consolidating the forum discussion.

**Comment by lognaturel** [comment]
https://docs.getodk.org/form-question-types/#background-audio-recording
