### ISSUE TITLE
Add native audio recording for audio type questions

### ISSUE THREAD

**Issue by lognaturel** [getodk/roadmap#59]
Forum thread: https://forum.getodk.org/t/adding-native-audio-recording-for-audio-type-questions/29347

- [x] User interviews
- [x] Collect experience design
- [x] Collect implementation (projected for v1.29)

### Use cases

- Recording interview responses
- Recording focus group discussions
- Recording environmental samples (e.g. birds, traffic, etc.)

### Feature details

- For each audio question, users should be able to start, pause, and stop recording, delete recording, play recording, pause playback 
- In General Settings, users should also be able to choose between different recording settings:
    - Record audio with various codecs, such as lossless (e.g. FLAC), a speech-optimized lossy codec, such as AMR, and a general-purpose lossy codec, such as MP3.
    - Choose recording quality (stereo/mono, sample rate, and bitrate as appropriate)

**Comment by tinok** [comment]
I added use cases and feature details to the issue description, consolidating the forum discussion.
